### ISSUE TITLE
広島銀行 2016-1Q 杉浦

### ISSUE THREAD

**Issue by nimura-tomoyuki** [mcms-cm/SI#19]

**Comment by tsugiura** [comment]
構築・テスト完了
お客様側 脆弱性診断完了

---残課題
顧客側:受け入れテスト
OPENSSL:設定変更
トレーニング:日時未定
本番切替:2016/6/25-26

**Comment by tsugiura** [comment]
OPENSSL:済

---残課題
顧客側:受け入れ判断
脆弱性対応:顧客判断待ち
トレーニング:2016/6/20-21
本番切替:2016/6/25-26

**Comment by tsugiura** [comment]
脆弱性対応:OK(IIJ吉田様から報告)2016/6/17

---残課題
顧客側:受け入れ判断
トレーニング:2016/6/20-21
本番切替:2016/7/2-7/3 (仮)
