### ISSUE TITLE
ファーストペンギン 認証方式変更 2016/1Q

### ISSUE THREAD

**Issue by NobuhiroShimomoto** [mcms-cm/SI#25]
4/11：変更問合せ、IP制限追加処理
4/18：SSL証明書更新（*.infotop.jp）⇒cmm/cmc/cml
4/25：切替作業（端末認証解除⇒IP制限へ）

**Comment by nimura-tomoyuki** [comment]
サブメンバは環境の副担当者の片野さん

**Comment by nimura-tomoyuki** [comment]
訂正InfoTopなので松田さんと下元さんで願います

主担当松田さん、副担当下元さん
