### ISSUE TITLE
謎のR8 リリース 

### ISSUE THREAD

**Issue by nimura-tomoyuki** [mcms-cm/SI#56]

**Comment by KatanoTakao** [comment]
藤巻先生からスキトラを受ける
リリース予定は5/27 or 5/30
あくまで予定、先方のDNSの設定次第

**Comment by KatanoTakao** [comment]
セットアップシートが来ないため5月中リリースはなし
F5にR8関連のパッチが適用されていないため、
5月30日週に適用予定
懸念事項はDmailプロセスの再起動が必須

**Comment by KatanoTakao** [comment]
6/6（月）19:30よりPatchインストール作業
