### ISSUE TITLE
zugockmail.pl IPアドレス変更 until June, 15 - to All mens, chnaging the IP  ”210.188.194.123”　=>　”182.236.92.133” / 210.188.194.119　＝> ”182.236.92.133”

### ISSUE THREAD

**Issue by nimura-tomoyuki** [mcms-cm/SI#65]

**Comment by nimura-tomoyuki** [comment]
zugock サーバ移管に伴う、IPアドレスの変更

 All mens, chnaging the IP  ”210.188.194.123”　=>　”182.236.92.133”

**Comment by KatanoTakao** [comment]
新生銀行、セブンCS環境変更完了
楽天証券は"210.188.194.123"が設定されていたものに関しては変更完了

下記環境は"210.188.194.119"が設定されていたため変更せず
Monex
Infotop
楽天証券

**Comment by nimura-tomoyuki** [comment]
210.188.194.119　＝> ”182.236.92.133” 願います。

現況：　大阪に２つの受信サーバがある
今後：　”182.236.92.133”（bit-isle） と　他のIDSにわかれる予定だが、大阪撤退時には、おそらく未定のままになるため、同じIPアドレスにしてください。

**Comment by KatanoTakao** [comment]
下記環境設定変更完了
Monex
Infotop
楽天証券

**Comment by mumatsuda** [comment]
下記の環境について ”210.188.194.123”　=>　”182.236.92.133” に変更作業が完了しました。
JAL
ANA 大量配信系
ANA 多言語環境
ANA 新メールサービス

**Comment by mumatsuda** [comment]
下記の環境について ”210.188.194.123”　=>　”182.236.92.133” に変更作業が完了しました。
フォーム１
ファーム２
ファーム6

**Comment by nimura-tomoyuki** [comment]
備忘：

宛先ドメインがxxxx@cm1.dclk.jp ,xxxxx@cm2.dclk.jp になっているものは、以下のように修正すること

xxxxx@cm2.dclk.jp
61.215.207.200

cm1.dclk.jp では、zugockが稼働していない（現在、片肺運転状態、将来は未定）であるため
